testbird:
  env_id: FlappyBird-v0
  memory_size: 100000
  batch_size: 32
  epsilon_initial: 0.8
  epsilon_decay: 0.99
  epsilon_min: 0.05
  network_sync_rate: 15
  learning_rate: 0.0005
  discount_factor: 0.95
  stop_training_at_reward: 50000
  fc1_units: 256
  env_make_params:
    use_lidar: True
  double_dqn: True
  dueling_dqn: True

adaptbird:
  env_id: FlappyBird-v0
  memory_size: 100000
  batch_size: 32
  epsilon_initial: .9
  epsilon_decay: .995
  epsilon_min: 0.01
  network_sync_rate: 10
  learning_rate: 0.0001
  discount_factor: 0.99
  stop_training_at_reward: 100000
  fc1_units: 512
  env_make_params:
    use_lidar: False
  double_dqn: True
  dueling_dqn: True
adaptbird2:
  env_id: FlappyBird-v0
  memory_size: 100000
  batch_size: 32
  epsilon_initial: .9
  epsilon_decay: .995
  epsilon_min: 0.01
  network_sync_rate: 10
  learning_rate: 0.0001
  discount_factor: 0.99
  stop_training_at_reward: 100000
  fc1_units: 512
  env_make_params:
    use_lidar: False
  double_dqn: True
  dueling_dqn: True
flappybird2:
  env_id: FlappyBird-v0
  replay_memory_size: 100000
  mini_batch_size: 32
  epsilon_init: .8
  epsilon_decay: 0.995
  epsilon_min: 0.01
  network_sync_rate: 10
  learning_rate_a: 0.0001
  discount_factor_g: 0.99
  stop_on_reward: 100000
  fc1_nodes: 512
  env_make_params:
    use_lidar: False
  enable_double_dqn: True
  enable_dueling_dqn: True
flappybird1:
  env_id: FlappyBird-v0
  replay_memory_size: 100000
  mini_batch_size: 32
  epsilon_init: .8
  epsilon_decay: 0.9995
  epsilon_min: 0.05
  network_sync_rate: 10
  learning_rate_a: 0.0001
  discount_factor_g: 0.99
  stop_on_reward: 100000
  fc1_nodes: 512
  env_make_params:
    use_lidar: False
  enable_double_dqn: True
  enable_dueling_dqn: True
